---
- hosts: all
  sudo: yes
  gather_facts: yes

  roles:
    - virtualenv.nfs
    - virtualenv.packer-debian

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
